name: CI

on:
  push:
  pull_request:
  # Run CI once a week even without code changes to ensure tests pass with
  # updated dependencies.
  schedule:
    - cron: '0 0 * * 5'
  # See:
  # * https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#scheduled-events
  # * https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07
  # Allow triggering a CI run from the web UI.
  workflow_dispatch:
  # See:
  # * https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
  # * https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        os:
        - { icon: ğŸ§, name: ubuntu }
        #- { icon: ğŸ, name: macos }
        #- { icon: ğŸ§Š, name: windows }
        pyver:
        - '3.6'
        - '3.7'
        - '3.8'
        - '3.9'
        - '3.10'
    runs-on: ${{ matrix.os.name }}-latest
    name: ${{ matrix.os.icon }} ${{ matrix.os.name }} | ${{ matrix.pyver }}
    steps:

    - name: ğŸ§° Repository Checkout
      uses: actions/checkout@v2

    - name: ğŸ Set up Python ${{ matrix.pyver }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.pyver }}

    - name: ğŸ› ï¸ Install dependencies
      run: |
        python -c "import sys; print(sys.version)"
        pip install tox

    - name: ğŸš§ Build package and run tests with tox
      run: tox -e py
